### ISSUE TITLE
Feature Request: Bracket Colorization variants

### ISSUE THREAD

**Issue by md1440** [adamjsx/arctis#1]
Hey,

love the theme. Personally I'd appreciate a little more high contrast/ or rainbowy bracket pair variant, for the default e.g for (()) I find so similar in its hue that I find it a little difficult to differentiate at times. I don't know whether this aligns with the vision of the project, but thought to bring it up.. in case it's resonant.

Thanks

Marc

**Comment by adamdotjs** [comment]
I'll take a look! The bracket colors used now were just pulled from Nord, so I haven't customized them much. I do agree there could be more contrast between them.

In the meantime, if you'd rather revert to the default colors, you can just add the following to your settings.json file:


    "workbench.colorCustomizations": {
        "[Arctis]": {
          "editorBracketHighlight.foreground1": "#ffd700",
          "editorBracketHighlight.foreground2": "#da70d6",
          "editorBracketHighlight.foreground3": "#179fff",
          "editorBracketHighlight.foreground4": "#00000000",
          "editorBracketHighlight.foreground5": "#00000000",
          "editorBracketHighlight.foreground6": "#00000000"
        }
    }

**Comment by adamdotjs** [comment]
Just pushed a new version with adjusted bracket colors (and a new variant). Let me know your thoughts.

**Comment by md1440** [comment]
Excellent, thank you. I find it easier on the eyes. Appreciate your effort!
